application: sweng-wiinotfit
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /login
  script: login.app

- url: /register
  script: register.app

- url: /submission
  script: add_submission.app

- url: /retrieve
  script: retrieve_submission.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: PIL
  version: "1.1.7"
