application: sweng-wiinotfit
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /login
  script: login.app

- url: /register
  script: register.app

- url: /submission
  script: add_submission.app

- url: /retrieve
  script: retrieve_submission.app

- url: /delete/user
  script: delete_user.app

- url: /delete/session
  script: delete_session.app

- url: /delete/submission
  script: delete_submission.app
  
- url: /vote
  script: submit_vote.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: PIL
  version: "1.1.7"
