application: sweng-wiinotfit
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
<<<<<<< HEAD
- url: /hello
  script: helloworld.app
  
=======
>>>>>>> 7fd71192286338bf8eba5bb39d4edd88c34ce452
- url: /login
  script: login.app
  
- url: /register
  script: register.app

- url: /newsubmission
	script: add_submission.app

libraries:
- name: webapp2
<<<<<<< HEAD
  version: "2.5.2"
=======
  version: "2.5.2"
>>>>>>> 7fd71192286338bf8eba5bb39d4edd88c34ce452
