application: sweng-wiinotfit
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /login
  script: login.app

- url: /register
  script: register.app

- url: /new_submission
	script: add_submission.app

- url: /what_is_new
	script: what_is_new.app

libraries:
- name: webapp2
  version: "2.5.2"
