application: sweng-wiinotfit
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /hello
  script: helloworld.app
  
- url: /login
  script: login.app
  
- url: /register
  script: register.app

libraries:
- name: webapp2
  version: "2.5.2"
